
apiVersion: v1
kind: Pod
metadata:
  name: caddy-pod
  labels:
    name: caddy-podv1
spec:
  containers:
  - name: caddy-container 
    image: bala699/csye7125:latest
    command: ["/bin/sh","-c"]
    args: ["caddy run --config $CADDY_PATH"]
    # command: ["echo $CADDY_PATH","caddy","run","--config","$CADDY_PATH","--adapter","caddyfile"]
    env: 
    - name: CADDY_PATH   
      valueFrom:
        configMapKeyRef:
          name: caddy-config
          key: CADDY_PATH
    ports: 
      - name: http-port
        containerPort: 3500
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /
        port: 3500
      initialDelaySeconds: 3
      successThreshold: 1
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /
        port: 3500
      initialDelaySeconds: 3
      successThreshold: 1
      failureThreshold: 3
  imagePullSecrets:
    - name: team12-dockerhub-secret

---
apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  selector:
    name: caddy-podv1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-port
  type: NodePort

---
# set type: LoadBalancer & start minikube tunnel

# if set NodePort minikube service caddy-service get url
