apiVersion: v1
data:
  .dockerconfigjson: base64encodedstring
kind: Secret
metadata:
  creationTimestamp: "2024-06-05T23:39:00Z"
  name: team12-dockerhub-secret
  namespace: default
  resourceVersion: "57377"
  uid: 7529019c-ba07-42cc-a1c4-fc41fa8e4adf
type: kubernetes.io/dockerconfigjson
